### ISSUE TITLE
Prefil `<?php\n\n` in textarea

### ISSUE THREAD

**Issue by ruudk** [RightCapitalHQ/php-ast-viewer#14]
First of all, I love this AST Viewer. I currently use it daily.

Would it be possible to add the following default value in the code textarea?

```php
<?php

```

This would make it easier to immediately test a code part.

**Comment by Yilun-Sun** [comment]
Hi @ruudk! Thank you for liking the AST Viewer; we hope it can be helpful to you. 

We are planning to add the following support: 
If the pasted content does not start with `<?php`, we will automatically prepend a `<?php\n`. This will perfectly support the case of pasting a code block.

**Comment by ruudk** [comment]
That's clever.

**Comment by Yilun-Sun** [comment]
We've implemented a simple version, you can give it a try =D.

**Comment by ruudk** [comment]
Super handy, thanks!
